/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSubstitutionRouteImport } from './routes/_app.substitution'
import { Route as AppSetupRouteImport } from './routes/_app.setup'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppTimetableIndexRouteImport } from './routes/_app.timetable.index'
import { Route as AppTimetableIdRouteImport } from './routes/_app.timetable.$id'
import { Route as AppTeacherIdRouteImport } from './routes/_app.teacher.$id'
import { Route as AppTimetableIdPreviewRouteImport } from './routes/_app.timetable.$id.preview'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSubstitutionRoute = AppSubstitutionRouteImport.update({
  id: '/substitution',
  path: '/substitution',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableIndexRoute = AppTimetableIndexRouteImport.update({
  id: '/timetable/',
  path: '/timetable/',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableIdRoute = AppTimetableIdRouteImport.update({
  id: '/timetable/$id',
  path: '/timetable/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherIdRoute = AppTeacherIdRouteImport.update({
  id: '/teacher/$id',
  path: '/teacher/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableIdPreviewRoute = AppTimetableIdPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AppTimetableIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/setup': typeof AppSetupRoute
  '/substitution': typeof AppSubstitutionRoute
  '/teacher/$id': typeof AppTeacherIdRoute
  '/timetable/$id': typeof AppTimetableIdRouteWithChildren
  '/timetable/': typeof AppTimetableIndexRoute
  '/timetable/$id/preview': typeof AppTimetableIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/setup': typeof AppSetupRoute
  '/substitution': typeof AppSubstitutionRoute
  '/teacher/$id': typeof AppTeacherIdRoute
  '/timetable/$id': typeof AppTimetableIdRouteWithChildren
  '/timetable': typeof AppTimetableIndexRoute
  '/timetable/$id/preview': typeof AppTimetableIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/setup': typeof AppSetupRoute
  '/_app/substitution': typeof AppSubstitutionRoute
  '/_app/teacher/$id': typeof AppTeacherIdRoute
  '/_app/timetable/$id': typeof AppTimetableIdRouteWithChildren
  '/_app/timetable/': typeof AppTimetableIndexRoute
  '/_app/timetable/$id/preview': typeof AppTimetableIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/setup'
    | '/substitution'
    | '/teacher/$id'
    | '/timetable/$id'
    | '/timetable/'
    | '/timetable/$id/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/setup'
    | '/substitution'
    | '/teacher/$id'
    | '/timetable/$id'
    | '/timetable'
    | '/timetable/$id/preview'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/setup'
    | '/_app/substitution'
    | '/_app/teacher/$id'
    | '/_app/timetable/$id'
    | '/_app/timetable/'
    | '/_app/timetable/$id/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/substitution': {
      id: '/_app/substitution'
      path: '/substitution'
      fullPath: '/substitution'
      preLoaderRoute: typeof AppSubstitutionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/setup': {
      id: '/_app/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timetable/': {
      id: '/_app/timetable/'
      path: '/timetable'
      fullPath: '/timetable/'
      preLoaderRoute: typeof AppTimetableIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timetable/$id': {
      id: '/_app/timetable/$id'
      path: '/timetable/$id'
      fullPath: '/timetable/$id'
      preLoaderRoute: typeof AppTimetableIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teacher/$id': {
      id: '/_app/teacher/$id'
      path: '/teacher/$id'
      fullPath: '/teacher/$id'
      preLoaderRoute: typeof AppTeacherIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timetable/$id/preview': {
      id: '/_app/timetable/$id/preview'
      path: '/preview'
      fullPath: '/timetable/$id/preview'
      preLoaderRoute: typeof AppTimetableIdPreviewRouteImport
      parentRoute: typeof AppTimetableIdRoute
    }
  }
}

interface AppTimetableIdRouteChildren {
  AppTimetableIdPreviewRoute: typeof AppTimetableIdPreviewRoute
}

const AppTimetableIdRouteChildren: AppTimetableIdRouteChildren = {
  AppTimetableIdPreviewRoute: AppTimetableIdPreviewRoute,
}

const AppTimetableIdRouteWithChildren = AppTimetableIdRoute._addFileChildren(
  AppTimetableIdRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppSetupRoute: typeof AppSetupRoute
  AppSubstitutionRoute: typeof AppSubstitutionRoute
  AppTeacherIdRoute: typeof AppTeacherIdRoute
  AppTimetableIdRoute: typeof AppTimetableIdRouteWithChildren
  AppTimetableIndexRoute: typeof AppTimetableIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppSetupRoute: AppSetupRoute,
  AppSubstitutionRoute: AppSubstitutionRoute,
  AppTeacherIdRoute: AppTeacherIdRoute,
  AppTimetableIdRoute: AppTimetableIdRouteWithChildren,
  AppTimetableIndexRoute: AppTimetableIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
